### ISSUE TITLE
Can't Infuse With Lapis!

### ISSUE THREAD

**Issue by Something-Went-Terribly-Wrong** [esapee/Essence-Armory#2]
When I try to infuse the amulet with "Essence Extractor" it wont let me! And when I break the pylons with lapis, it turns them into ink sacs!
![2016-07-16_23 04 01](https://cloud.githubusercontent.com/assets/19368215/16898467/a7df2ada-4ba9-11e6-919a-1ebd143de07b.png)

**Comment by Something-Went-Terribly-Wrong** [comment]
As a side note, I am currently running version 1.0.0 for 1.7.10. It was the newest version I could find (for 1.7.10).

**Comment by murapix** [comment]
Yeah, that's the last version for 1.7.10. Them turning into ink sacs is a bug, I'll see if I can fix that.

As for the infusion not working, move the pedestals down one block.

**Comment by murapix** [comment]
This was something I'd already fixed in the 1.8.9 versions, but forgot to port back to 1.7.10. I've uploaded another version with the fix, which will be available as soon as Curse approves it.

**Comment by Something-Went-Terribly-Wrong** [comment]
THANK YOU SO MUCH <3

I LOVE UR MOD BTW

**Comment by murapix** [comment]
Aw, thanks! It's been a lot of work to get it to this point, and I'm always happy to hear that my occasional user likes my work.
